stages:
  - build
  - release

variables:
  RELEASES_DIR: "releases"

repackage:
  stage: build
  image: php:8.3-cli
  only:
    - main
  before_script:
    - apt-get update && apt-get install -y git zip unzip
    - docker-php-ext-install pcntl
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - mv composer.phar /usr/local/bin/composer
    - composer install --no-progress --prefer-dist
  script:
    - echo "Repackaging your application into a PHAR file..."
    - vendor/bin/castor repack --app-name=cpamg
    - mkdir -p ${RELEASES_DIR}
    - mv cpamg.phar ${RELEASES_DIR}/cpamg.phar
    - echo "Repackaging completed."
  artifacts:
    paths:
      - ${RELEASES_DIR}/cpamg.phar

create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    - tags
  script:
    - echo "Creating release for tag ${CI_COMMIT_TAG}..."
    - |
      release-cli create --name "Release ${CI_COMMIT_TAG}" --description "Release ${CI_COMMIT_TAG}" \
      --tag-name "${CI_COMMIT_TAG}" --ref "${CI_COMMIT_REF_NAME}" \
      --assets-link "{\"name\":\"cpamg.phar\",\"url\":\"${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/releases/cpamg.phar\"}"
    - echo "Release created."

